# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# Deny crates with security vulnerabilities
version = 2
ignore = [
    # paste is unmaintained but it's a transitive dependency of ratatui
    # ratatui is actively maintained and will update paste or replace it when needed
    "RUSTSEC-2024-0436",
]

[licenses]
# List of explicitly allowed licenses
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
]
# Confidence threshold for license detection
confidence-threshold = 0.8

[bans]
# Deny multiple versions of the same crate
multiple-versions = "warn"
# Deny wildcard dependencies
wildcards = "allow"
# List of crates that are allowed to have multiple versions
skip = []
# List of explicitly banned crates
deny = []

[sources]
# Deny crates from unknown registries
unknown-registry = "deny"
# Deny crates from git repositories
unknown-git = "deny"
# Allow crates from these git repositories
allow-git = [
    "https://github.com/helix-editor/helix",
]
