# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# Threshold for security vulnerabilities
vulnerability = "deny"
# Threshold for unmaintained crates
unmaintained = "warn"
# Threshold for crates marked as unsound
unsound = "warn"
# Threshold for yanked crates
yanked = "deny"
# Threshold for crates with security notices
notice = "warn"

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
]
# Confidence threshold for license detection
confidence-threshold = 0.8
# Allow 1 or more licenses on a per-crate basis
exceptions = []

[bans]
# Deny multiple versions of the same crate
multiple-versions = "warn"
# Deny wildcard dependencies
wildcards = "deny"
# Highlight crates that are not available on crates.io
allow-wildcard-paths = false
# List of crates that are allowed to have multiple versions
skip = []
# List of explicitly banned crates
deny = []

[sources]
# Deny crates from unknown registries
unknown-registry = "deny"
# Deny crates from git repositories
unknown-git = "deny"
# Allow crates from these git repositories
allow-git = [
    "https://github.com/helix-editor/helix",
]
