# Line Join Operations
# Scenarios covering joining lines

[[scenarios]]
id = "join_lines_001"
name = "Join two lines"
description = "Join the current line with the line below"

[scenarios.setup]
file_content = "Hello\nWorld"
cursor_position = [0, 0]

[scenarios.target]
file_content = "Hello World"
cursor_position = [0, 0]

[scenarios.solution]
commands = ["J"]
description = "Press 'J' to join lines"

hints = [
    "'J' joins the current line with the next line",
    "A space is automatically added between the joined lines",
]

[scenarios.scoring]
optimal_count = 1
max_points = 100
tolerance = 0
