# Document-Level Navigation
# Scenarios covering document-wide movement

[[scenarios]]
id = "document_navigation_001"
name = "Jump to document start"
description = "Navigate to the beginning of the document"

[scenarios.setup]
file_content = """Line 1
Line 2
Line 3
Line 4
Line 5"""
cursor_position = [4, 0]

[scenarios.target]
file_content = """Line 1
Line 2
Line 3
Line 4
Line 5"""
cursor_position = [0, 0]

[scenarios.solution]
commands = ["g", "g"]
description = "Press 'gg' to jump to document start"

hints = [
    "'gg' jumps to the first line of the document",
    "'G' jumps to the last line of the document",
]

[scenarios.scoring]
optimal_count = 2
max_points = 100
tolerance = 1

[[scenarios]]
id = "document_end_001"
name = "Jump to document end"
description = "Navigate to the end of the document"

[scenarios.setup]
file_content = """First line
Second line
Third line
Fourth line
Last line"""
cursor_position = [0, 0]

[scenarios.target]
file_content = """First line
Second line
Third line
Fourth line
Last line"""
cursor_position = [4, 0]

[scenarios.solution]
commands = ["G"]
description = "Press 'G' to jump to document end"

hints = [
    "'G' jumps to the last line of the document",
    "'gg' jumps to the first line",
]

[scenarios.scoring]
optimal_count = 1
max_points = 100
tolerance = 0
